name: my_home
description: Team Project from Operating Systems Course

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  parse_server_sdk_flutter: ^3.1.3
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^1.1.6
  dio: ^4.0.6
  dio_retry_plus: ^1.0.2
  connectivity_plus: ^2.3.8
  dio_logging_interceptor: ^1.0.1
  cached_network_image: ^3.2.2
  glass_kit: ^2.0.1
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  hive: ^2.0.4
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: ^2.2.1
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/logo/
